services:
  - type: web
    name: belka-pmr-booking
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python server.py"
    envVars:
      - key: FLASK_ENV
        value: production